parameters:
  maria.event_listener.trigger.class: SweetCode\MariaBundle\Listener\TriggerEventListener

  maria.service_factory.matcher.class: SweetCode\MariaBundle\Matcher\MatcherFactory
  maria.service_factory.operator.class: SweetCode\MariaBundle\Operator\OperatorFactory

services:
  maria.service_factory.operator:
      class: '%maria.service_factory.operator.class%'

  maria.service_factory.matcher:
      class: "%maria.service_factory.matcher.class%"
      arguments:
        - '@maria.service_factory.operator'
