services:
  maria.matcher.any:
    class: "%maria.matcher.any.class%"

  maria.matcher.all:
    class: "%maria.matcher.all.class%"

  maria.matcher.first:
    class: "%maria.matcher.first.class%"

  maria.matcher.last:
    class: "%maria.matcher.last.class%"

  maria.matcher.none:
    class: "%maria.matcher.none.class%"