language: php

php:
  - 7.2
  - 7.1
  - 7.0
  - 5.6
  - 5.6

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - phpenv rehash
  - composer install --dev

script:
  - find ./src/ -name "*.php" -exec php -l {} \;
  - vendor/bin/phpcs --standard=PSR2 --report=full src
  - vendor/bin/phpunit
