language: php

php:
#  - 7.4
  - 7.3
  - 7.2
  - 7.1
#  - 7.0
#  - 5.6

before_script:
  - phpenv rehash
  - composer install --dev

script:
#  - find ./src/ -name "*.php" -exec php -l {} \;
  - vendor/bin/phpunit
